### ISSUE TITLE
Weird investment results caused by temporal block settings

### ISSUE THREAD

**Issue by nnhjy** [Spine-project/SpineOpt.jl#496] opened 2022-10-13 18:36 UTC
The issue can be seen in the result of [this SpineOpt sample](https://github.com/Spine-project/SpineOpt.jl/files/9779493/Data.Store.input.2.zip). There are two scenarios, with the only difference in the start time of the temporal block for investment decisions (`inv`): one begins at the same time as the operational temporal block (`opt`); the other begins one hour later.  Investment in `unitA` is needed from the 2nd hour on. 

Investment results under the synchronised investment temporal block look okay. But under the shorter investment temporal block, the output of `unit_invested` becomes constantly 0, despite new capacity being actually invested (see `unit_available` in output). And the de facto investment decisions in two scenarios are slightly different (see `unit_invested_available` in output).

**Comment by mihlema** [comment] 2022-10-17 16:49
I think the model is sort of working as intended, maybe it is more of a question on how to realize the desired functionality.
The problem with the model you describe is that the `unit_invested_transition` constraint fails, as there is no "history" investment variables for `2000-01-01T00:00~>2000-01-01T01:00`; hence the model has a degree of freedom there. 

I think for your use case this could easily be fixed by having the investment temporal block start at the beginning of the optimization, but defining a TimeSeries `fix_units_invested` for the first timestep of the optimization.

**Comment by nnhjy** [comment] 2022-10-18 09:17
Thanks! The approach works to realise the need to model units that are supposed to be available for investment later than the beginning of the model horizon. 

As per the need for "history" investment, does it also mean a temporal block starting simultaneously as the model is necessary for investment?

**Comment by mihlema** [comment] 2022-10-18 09:24
> As per the need for "history" investment, does it also mean a temporal block starting simultaneously as the model is necessary for investment?
I'm not entirely following what you mean with that. Could you clarify?

**Comment by nnhjy** [comment] 2022-10-18 16:23
To make the `unit_invested_transition` constraint work correctly, do we always need to set the temporal block for investment decisions to start at the same time as the start time of a model?

**Comment by mihlema** [comment] 2022-10-20 09:17
I'll close this issue (feel free to reopen it if questions remain). 
If you're interested and have some spare time, it would be great if you'd like to add a section on this to the documentation.

**Closed by mihlema** 2022-10-20 09:17 UTC
Labels: invalid, investments

**Comment by nnhjy** [comment] 2022-10-20 14:28
Thanks for the explanation! I think I got the main idea. I am interested in the details about how the historical values for variables (particularly the investment-related ones) are created. Could you point me to the codes where the model decides (not)/to create historical values?
